### PR TITLE
Open log file when clicking error indicator

### PR DESCRIPTION
**Pull request by thomasjo**
See https://github.com/thomasjo/atom-latex/issues/82.

- [x] Open log file when clicking indicator.
- [x] Scroll to first error after opening log file.

/cc @nscaife @myfavouritekk

### CODE REVIEW

**Comment by nscaife** [comment]
@thomasjo First commit works for me! Log opened on click.

**Comment by thomasjo** [comment]
Does it make sense to destroy the error indicator when clicked? Maybe it's valuable to just keep the current behavior of persisting until the next build? Just thinking if the user closes the log file, but would prefer to open it again without navigating to the file or running another build.

**Comment by nscaife** [comment]
I can see some great uses for leaving it, but I wouldn't open the log more than once.  If it's already open, just switch to that tab.

**Comment by thomasjo** [comment]
> If it's already open, just switch to that tab.

Yep, that's the current behavior :smile:

**Pull request merged**
