### PR TITLE
Dependency version bumps and log toggle

### PR DESCRIPTION
**Pull request by StaticRocket**
- Bump dependencies to:
  - Satisfy David
  - Avoid `lodash`'s prototype pollution vulnerability
- Change status click activity to toggle in order to make log review and dismissal faster in terms of workflow

All package commands were tested with an IEEEtran LaTeX template on the following platforms for stability:
- [x] Arch Linux (Kernel 4.18.12-arch1-1-ARCH)
- [x] Windows 10 (1803)

### CODE REVIEW

**Comment by StaticRocket** [comment]
So apparently Travis doesn't like that whatever is running no longer wants to be headless and AppVeyor doesn't like the Disposable "class" in the Atom beta channel. I tried playing with Travis's settings, but no dice. I don't even know what's going on with AppVeyor and ATOM_CHANNEL=beta. I get the original linting errors, but now it's just odd.

**Comment by StaticRocket** [comment]
I reverted my changes to Travis and AppVeyor. My commits work on my two computers but for whatever reason Travis doesn't like it. ¯\\_(ツ)_/¯

**Comment by thomasjo** [comment]
I'll try to find some time to properly review and test this during the weekend.
Thanks for being so patient! :bowing_man:

**Comment by StaticRocket** [comment]
Entirely sorry for this dumpster fire of a PR. I'm spending some time to learn about CI before I try to do anything else with this.

**Pull request closed without merging**
