### PR TITLE
Code generation features

### PR DESCRIPTION
**Pull request by mpilman**
I copied a few code generation features from Sublime:

cmd-shidt-c puts the selected text into \cmd{#{selected text}} and selects the string cmd in Atom

cmd-shift-e,b,u, or t puts the selected text into a emph, bold, underline or texttt command

cmd-shift-h puts it into a new environment

cmd-shift-c,e create a new command/environment with the same name as the word under/before the cursor. If there are several cursors, it will do so for each cursor.

These features are “stolen” from Sublime latextools and have proven very handy for me. Please merge those into the main branch (or tell me what needs to be changed).

### CODE REVIEW

**Comment by thomasjo** [comment]
Similar story here as with #55; check out [pull-56 branch](https://github.com/thomasjo/atom-latex/tree/pull-56).

**Comment by thomasjo** [comment]
Had some quick glances at the code while I was resolving merge conflicts, and I have some initial concerns over the level of code duplication. I will see if I can get some time over the weekend to give more specific "line-by-line" level of feedback.

**Comment by mpilman** [comment]
Sorry for my late reply (I was sick the last few days...).

I tried to polish the code a bit. It is still not beautiful but I think I improved on the quality. This is the first time I ever code in CoffeeScript (or for Atom). I would therefore appreciate specific pointers which part should get improvement.

Please see my [new pull request](https://github.com/thomasjo/atom-latex/pull/59)

**Comment by thomasjo** [comment]
Closing for the same reason as https://github.com/thomasjo/atom-latex/pull/55#issuecomment-113904122

**Pull request closed without merging**
