### PR TITLE
Add crtl-alt-c => clean shortcut

### PR DESCRIPTION
**Pull request by balu-**

### CODE REVIEW

**Comment by nscaife** [comment]
I originally omitted this to prevent someone from accidentally cleaning, since there's no confirmation before it irrevocably deletes the files.  The defaults are fairly safe, though, and shouldn't delete something that can't be regenerated.

**Comment by balu-** [comment]
Oh, I see…
just thought it was missing and tried to be a good open source citizen :wink:

**Comment by nscaife** [comment]
I certainly don't see an issue with it, and it's great that you submitted a pull request (I wish more people would!).

**Comment by thomasjo** [comment]
Thanks! I'm a little bit reluctant due to the same reason as @nscaife, but if it becomes a problem we can fix it then.

**Pull request merged**
