### PR TITLE
Appveyor rewrite for #66

### PR DESCRIPTION
**Pull request by nscaife**
I spent some time today rewriting the AppVeyor YAML to assist with #66.  More specifically, I removed the Chocolatey requirement and wrapped almost everything in retry logic.  I still ran into a couple of random AppVeyor errors where the Atom install didn't complete and/or the TeX download failed, but the retry seems to resolve the issue.

### CODE REVIEW

**Comment by thomasjo** [comment]
Thanks for helping out with this — brilliant! Looks a lot less fragile now, but there is sadly still some AppVeyor issues. I really wish I knew what the cause of each failure was; at times it's even failing to download my pre-packaged TeX Live distribution, almost as if the build agent loses network connectivity. And, as you mentioned, sometimes the actual Atom install fails.

The free build agents provided AppVeyor are vastly underpowered compared to the Travis counterpart. Merely extracting the TeX distribution takes around two times longer, and the downloads are slower...

---
*Unless we can sort out the issues soon, I will kill off the AppVeyor CI builds, since at this point it's only noise and provides zero benefit.*

**Comment by nscaife** [comment]
The AppVeyor builds don't make any sense.  On the same commit, it will work fine for a build and then fail the next time.  Before the pull request, that commit built with no issues.

I agree it's not worth the additional time and effort to get these working.

**Comment by thomasjo** [comment]
Regardless of AppVeyor builds being flakey or not, I really appreciate the effort you've put into getting them working. I'll merge this PR before I kill the builds.

**Comment by thomasjo** [comment]
Merged in c9caeab818386a518557573f10f502522aed1b74. Thanks!

**Pull request closed without merging**
